
INSERT INTO SUPPLIER (SUPP_ID, NAME) 
  VALUES (1, 'DEPOT1') ;

INSERT INTO SUPPLIER (SUPP_ID, NAME) 
  VALUES (2, 'DEPOT2') ;
  
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (1, 20, 1, 1) ;
 
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (2, 2, 2, 1) ;
 
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (3, 2, 1, 1) ;
 
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (10, 11, 2, 1) ;
 
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (20, 200, 1, 1) ;
  
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (21, 0, 2, 1) ;
  
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (30, 11, 1, 1) ;
  
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (31, 2, 2, 1) ;
  
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (40, 14, 1, 1) ;
  
INSERT INTO PRODUCT (SKU, INSTOCK, SUPP_ID, VERSION) 
  VALUES (41, 1, 2, 1) ;
